name:                web-toolkit
version:             0.1.0.0
github:              "prasmussen/web-toolkit"
license:             BSD3
author:              "Petter Rasmussen"
maintainer:          "petter@hask.no"
copyright:           "2019 Petter Rasmussen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/prasmussen/web-toolkit#readme>

dependencies:
- base >= 4.7 && < 5
- safe

library:
  source-dirs: src

tests:
  web-toolkit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - web-toolkit
