name:                web-core-base
version:             0.1.0.0
github:              "prasmussen/web-core"
license:             BSD3
author:              "Petter Rasmussen"
maintainer:          "petter@hask.no"
copyright:           "2019 Petter Rasmussen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/prasmussen/web-core#readme>

dependencies:
- base >= 4.7 && < 5
- safe
- transformers
- either
- text
- bytestring
- binary-parser
- base64-bytestring
- clientsession
- http-api-data
- cookie
- time
- binary
- wai
- wai-app-static
- warp
- http-types
- aeson
- servant-server
- stm
- swagger2
- servant-swagger
- servant-swagger-ui
- servant-swagger-ui-core
- lens
- cryptonite
- argon2
- text-short
- filepath
- directory
- utf8-string
- warp-systemd
- http-client
- http-client-tls

library:
  source-dirs: src
  ghc-options:
  - -Weverything
  - -Wno-missed-specialisations
  - -Wno-all-missed-specialisations
  - -Wno-unsafe
  - -Wno-safe
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-missing-import-lists
  - -Wno-implicit-prelude

tests:
  web-core-base-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - web-core-base
